spring.application.name=projecthub-api

spring.datasource.url=jdbc:postgresql://localhost:5432/projecthub
spring.datasource.username=admin
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE